#!/bin/bash
[ -z "$CFILE" ] || [ ! -f "$CFILE" ] && echo "Error: \$CFILE is unset or doesn't exist." || gcc -c "$CFILE" -o "${CFILE%.*}.o" && echo "Compilation of $CFILE complete. Object file saved as '${CFILE%.*}.o'."

